#include "DeviceListWgt.h"
#include <QFrame>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QStyle>
#include <QVBoxLayout>
#include "StyleLoader.h"
namespace{QLabel*L(const QString&t,const QString&n,QWidget*p){auto*l=new QLabel(t,p);l->setObjectName(n);l->setWordWrap(true);return l;}}
DeviceListWgt::DeviceListWgt(QWidget*p):QWidget(p){setAttribute(Qt::WA_StyledBackground);setFixedSize(600,510);setObjectName("DeviceListWgt");auto*title=L(QString::fromUtf8("设备列表"),"devicePageTitle",this);auto*desc=L(QString::fromUtf8("这里显示本客户端的登录身份和信令注册状态。"),"devicePageDescription",this);emptyState_=new QWidget(this);emptyState_->setObjectName("deviceEmptyState");auto*el=new QVBoxLayout(emptyState_);el->setContentsMargins(28,24,28,24);el->addWidget(L(QString::fromUtf8("还没有登录设备"),"emptyTitle",emptyState_));el->addWidget(L(QString::fromUtf8("请先登录。登录成功后，此处会显示本机设备及其注册状态。"),"emptyDescription",emptyState_));deviceSummary_=new QFrame(this);deviceSummary_->setObjectName("deviceSummary");auto*sl=new QVBoxLayout(deviceSummary_);sl->setContentsMargins(28,24,28,24);sl->setSpacing(18);auto*sh=new QHBoxLayout();sh->addWidget(L(QString::fromUtf8("当前登录设备"),"deviceSummaryTitle",deviceSummary_));sh->addStretch();statusValue_=L(QString::fromUtf8("正在注册设备"),"deviceStatus",deviceSummary_);sh->addWidget(statusValue_);sl->addLayout(sh);auto*d=new QGridLayout();d->setHorizontalSpacing(32);d->setVerticalSpacing(16);d->addWidget(L(QString::fromUtf8("登录账号"),"deviceFieldLabel",deviceSummary_),0,0);accountValue_=L("-","deviceFieldValue",deviceSummary_);d->addWidget(accountValue_,0,1);d->addWidget(L(QString::fromUtf8("设备识别码"),"deviceFieldLabel",deviceSummary_),1,0);codeValue_=L("-","deviceCodeValue",deviceSummary_);d->addWidget(codeValue_,1,1);d->setColumnStretch(1,1);sl->addLayout(d);statusDetail_=L(QString::fromUtf8("正在等待信令服务器确认设备注册。"),"deviceHint",deviceSummary_);sl->addWidget(statusDetail_);deviceSummary_->hide();auto*layout=new QVBoxLayout(this);layout->setContentsMargins(48,44,48,48);layout->setSpacing(0);layout->addWidget(title);layout->addSpacing(8);layout->addWidget(desc);layout->addSpacing(32);layout->addWidget(emptyState_);layout->addWidget(deviceSummary_);layout->addStretch();setLayout(layout);StyleLoader::getInstance()->loadStyle(":/UI/brown/main.css",this);}
void DeviceListWgt::showLoggedInDevice(const std::string&a,const std::string&c){accountValue_->setText(QString::fromStdString(a).trimmed());codeValue_->setText(QString::fromStdString(c).trimmed());emptyState_->hide();deviceSummary_->show();setRegistrationState(QString::fromUtf8("正在注册设备"),QString::fromUtf8("正在连接信令服务器。"),"pending");}
void DeviceListWgt::setRegistrationState(const QString&s,const QString&d,const QString&t){statusValue_->setText(s);statusValue_->setProperty("tone",t);statusValue_->style()->unpolish(statusValue_);statusValue_->style()->polish(statusValue_);statusDetail_->setText(d);}